using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace JiiLib.Media.Mp3
{
    internal static class Constants
    {
        internal const string AENC = "AENC";
        internal const string APIC = "APIC";
        internal const string ASPI = "ASPI";
        internal const string COMM = "COMM";
        internal const string COMR = "COMR";
        internal const string ENCR = "ENCR";
        internal const string EQU2 = "EQU2";
        internal const string ETCO = "ETCO";
        internal const string GEOB = "GEOB";
        internal const string GRID = "GRID";
        internal const string LINK = "LINK";
        internal const string MCDI = "MCDI";
        internal const string MLLT = "MLLT";
        internal const string OWNE = "OWNE";
        internal const string PRIV = "PRIV";
        internal const string PCNT = "PCNT";
        internal const string POPM = "POPM";
        internal const string POSS = "POSS";
        internal const string RBUF = "RBUF";
        internal const string RVA2 = "RVA2";
        internal const string RVRB = "RVRB";
        internal const string SEEK = "SEEK";
        internal const string SIGN = "SIGN";
        internal const string SYLT = "SYLT";
        internal const string SYTC = "SYTC";
        internal const string TALB = "TALB";
        internal const string TBPM = "TBPM";
        internal const string TCOM = "TCOM";
        internal const string TCON = "TCON";
        internal const string TCOP = "TCOP";
        internal const string TDEN = "TDEN";
        internal const string TDLY = "TDLY";
        internal const string TDOR = "TDOR";
        internal const string TDRC = "TDRC";
        internal const string TDRL = "TDRL";
        internal const string TDTG = "TDTG";
        internal const string TENC = "TENC";
        internal const string TEXT = "TEXT";
        internal const string TFLT = "TFLT";
        internal const string TIPL = "TIPL";
        internal const string TIT1 = "TIT1";
        internal const string TIT2 = "TIT2";
        internal const string TIT3 = "TIT3";
        internal const string TKEY = "TKEY";
        internal const string TLAN = "TLAN";
        internal const string TLEN = "TLEN";
        internal const string TMCL = "TMCL";
        internal const string TMED = "TMED";
        internal const string TMOO = "TMOO";
        internal const string TOAL = "TOAL";
        internal const string TOFN = "TOFN";
        internal const string TOLY = "TOLY";
        internal const string TOPE = "TOPE";
        internal const string TOWN = "TOWN";
        internal const string TPE1 = "TPE1";
        internal const string TPE2 = "TPE2";
        internal const string TPE3 = "TPE3";
        internal const string TPE4 = "TPE4";
        internal const string TPOS = "TPOS";
        internal const string TPRO = "TPRO";
        internal const string TPUB = "TPUB";
        internal const string TRCK = "TRCK";
        internal const string TRSN = "TRSN";
        internal const string TRSO = "TRSO";
        internal const string TSOA = "TSOA";
        internal const string TSOP = "TSOP";
        internal const string TSOT = "TSOT";
        internal const string TSRC = "TSRC";
        internal const string TSSE = "TSSE";
        internal const string TSST = "TSST";
        internal const string TXXX = "TXXX";
        internal const string UFID = "UFID";
        internal const string USER = "USER";
        internal const string USLT = "USLT";
        internal const string WCOM = "WCOM";
        internal const string WCOP = "WCOP";
        internal const string WOAF = "WOAF";
        internal const string WOAR = "WOAR";
        internal const string WOAS = "WOAS";
        internal const string WORS = "WORS";
        internal const string WPAY = "WPAY";
        internal const string WPUB = "WPUB";
        internal const string WXXX = "WXXX";
    }
}
